import Head from 'next/head'
import Link from 'next/link'
import { Card } from 'react-bootstrap'
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="m-3">
        <h1 className="m-1">
          HOME
        </h1>

        <Container>
          <Row> 
            <Col sm={12} md={6}>
              <Link href={{ pathname: "/Contrato" }}>
                <Card className="m-1 pe-auto" border="primary" style={{ width: 'auto' }}>
                  <Card.Header>CREAR CONTRATO</Card.Header>
                  <Card.Body>
                    <Card.Title>CREAR CONTRATO</Card.Title>
                    <Card.Text>
                      Some quick example text to build on the card title and make up the
                      bulk of the card content.
                    </Card.Text>
                  </Card.Body>
                </Card>
              </Link>
            </Col>
            <Col sm={12} md={6}>
              <Link href={{ pathname: "/Contrato" }}>
              <Card className="m-1 pe-auto" border="primary" style={{ width: 'auto' }}>
                  <Card.Header>CREAR RECIBO</Card.Header>
                  <Card.Body>
                    <Card.Title>CREAR RECIBO</Card.Title>
                    <Card.Text>
                      Some quick example text to build on the card title and make up the
                      bulk of the card content.
                    </Card.Text>
                  </Card.Body>
                </Card>
              </Link>
            </Col>
          </Row>
        </Container>
      </main>
    </div>
  )
}
